# LISTE DES PROPRIETES SPRING-BOOT: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

#SPRING BOOT VIEW RESOLVER PATH
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#CONTEXT PATH DU DISPATCHER SERVLET
spring.mvc.servlet.path=/