# LISTE DES PROPRIETES SPRING-BOOT: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

#SPRING BOOT VIEW RESOLVER PATH
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#CONTEXT PATH DU DISPATCHER SERVLET
spring.mvc.servlet.path=/

# LISTE DES PROPRIETES https://springdoc.org/#properties
## String, For custom path of the swagger-ui HTML documentation.
springdoc.swagger-ui.path=/swagger.html
## List of Strings. The list of packages to scan (comma separated)
springdoc.packages-to-scan=fr.sparna.rdf.xls2rdf.web.rest
server.forward-headers-strategy=framework